#include "myMesh.h"
#include <fstream>
#include <iostream>
#include <sstream>
#include <map>
#include <utility>
#include <GL/glew.h>
#include "myVector3D.h"
#include <set>

using namespace std;

myMesh::myMesh(void)
{
	/**** TODO ****/
}


myMesh::~myMesh(void)
{
	/**** TODO ****/
	clear();
}

void myMesh::clear()
{
	for (unsigned int i = 0; i < vertices.size(); i++) if (vertices[i]) delete vertices[i];
	for (unsigned int i = 0; i < halfedges.size(); i++) if (halfedges[i]) delete halfedges[i];
	for (unsigned int i = 0; i < faces.size(); i++) if (faces[i]) delete faces[i];

	vector<myVertex *> empty_vertices;    vertices.swap(empty_vertices);
	vector<myHalfedge *> empty_halfedges; halfedges.swap(empty_halfedges);
	vector<myFace *> empty_faces;         faces.swap(empty_faces);
}

void myMesh::checkMesh()
{
	//redoed this function with a list of checks generated by AI, and implemented by myself + verified by AI
	int errors = 0;

	// 1. check twin existence
	vector<myHalfedge *>::iterator it;
	for (it = halfedges.begin(); it != halfedges.end(); it++)
	{
		if ((*it)->twin == NULL)
			break;
	}
	if (it != halfedges.end()) {
		cout << "Error! Not all edges have their twins!\n";
		errors++;
	}
	else cout << "Each edge has a twin!\n";

	// 2. check twin symmetry：e->twin->twin == e
	int badTwinSym = 0;
	for (it = halfedges.begin(); it != halfedges.end(); it++)
	{
		if ((*it)->twin) {
			if ((*it)->twin->twin != *it) {
				badTwinSym++;
			}
		}
	}
	if (badTwinSym > 0) {
		cout << badTwinSym << " halfedge(s) have non-symmetric twin.\n";
		errors++;
	} else {
		cout << "All twin relationships are symmetric.\n";
	}

	// 3. check next/prev consistency
	int badNextPrev = 0;
	for (it = halfedges.begin(); it != halfedges.end(); it++){
		if ((*it)->next) {
			if ((*it)->next->prev != *it) {
				badNextPrev++;
			}
		}
		if ((*it)->prev) {
			if ((*it)->prev->next != *it) {
				badNextPrev++;
			}
		}
	}
	if (badNextPrev > 0) {
		cout <<badNextPrev << " next/prev inconsistency(ies).\n";
		errors++;
	} else {
		cout << "next/prev are consistent.\n";
	}

	// 4. check each halfedge has an adjacent face
	int noFace = 0;
	for (it = halfedges.begin(); it != halfedges.end(); it++) {
		if (!(*it)->adjacent_face) noFace++;
	}
	if (noFace > 0) {
		cout << noFace << " halfedge(s) have no adjacent face.\n";
		errors++;
	} else {
		cout << "All halfedges have an adjacent face.\n";
	}

	// 5. check each halfedge has a source vertex
	int noSource = 0;
	for (it = halfedges.begin(); it != halfedges.end(); it++) {
		if (!(*it)->source) noSource++;
	}
	if (noSource > 0) {
		cout << noSource << " halfedge(s) have no source vertex.\n";
		errors++;
	} else {
		cout << "All halfedges have a source vertex.\n";
	}

	// 6. check twin direction
	int badDir = 0;
	for (it = halfedges.begin(); it != halfedges.end(); it++) {
		if (it != halfedges.end() && (*it)->twin) {
			if (!(*it)->next || !(*it)->twin->source || !(*it)->next->source) {
				badDir++;
				continue;
			}
			if ((*it)->twin->source != (*it)->next->source) {
				badDir++;
			}
		}
	}
	if (badDir > 0) {
		cout << badDir << " halfedge(s) twin direction mismatch (twin->source != next->source).\n";
		errors++;
	} else {
		cout << "All twin directions are correct.\n";
	}

	// 7. Check face loops are closed
	int badLoop = 0;
	for (auto *f : faces) {
		if (!f->adjacent_halfedge) { badLoop++; continue; }
		myHalfedge *start = f->adjacent_halfedge;
		myHalfedge *cur = start;
		int count = 0;
		do {
			if (!cur->next) { badLoop++; break; }
			cur = cur->next;
			if (++count > (int)halfedges.size()) { badLoop++; break; }
		} while (cur != start);
	}
	if (badLoop > 0) {
		cout << badLoop << " face(s) have broken halfedge loop.\n";
		errors++;
	} else {
		cout << "All face loops are closed.\n";
	}

}


bool myMesh::readFile(std::string filename)
{
	string s, t, u;
	vector<int> faceids;
	myHalfedge **hedges;

	ifstream fin(filename);
	if (!fin.is_open()) {
		cout << "Unable to open file!\n";
		return false;
	}
	name = filename;

	map<pair<int, int>, myHalfedge *> twin_map;
	map<pair<int, int>, myHalfedge *>::iterator it;

	while (getline(fin, s))
	{
		stringstream myline(s);
		t = "";
		myline >> t;
		if (t == "g") {}
		else if (t == "v")
		{
			float x, y, z;
			myline >> x >> y >> z;
			myPoint3D *p = new myPoint3D(x, y, z);
			myVertex *v = new myVertex();
			v->point = p;
			vertices.push_back(v);
		}
		else if (t == "mtllib") {}
		else if (t == "usemtl") {}
		else if (t == "s") {}
		else if (t == "f")
		{
			myFace *f = new myFace();
			faceids.clear();
			while (myline >> u) {
				int v_idx = atoi((u.substr(0, u.find("/"))).c_str());
					faceids.push_back(v_idx - 1);
			}
			hedges = new myHalfedge*[faceids.size()];
			for (unsigned int i = 0; i < faceids.size(); i++) {
				int v_start = faceids[i];
				int v_end = faceids[(i + 1) % faceids.size()];

				myHalfedge *e = new myHalfedge();
				hedges[i] = e;
				e->source = vertices[faceids[i]];
				vertices[faceids[i]]->originof = e;
				e->adjacent_face = f;
				halfedges.push_back(e);

				it = twin_map.find(make_pair(v_end, v_start));
				if (it != twin_map.end()) {
					myHalfedge *twin_e = it->second;
					e->twin = twin_e;
					twin_e->twin = e;
				}else {
					pair<int, int> my_key(v_start, v_end);
					twin_map[my_key] = e;
				} //used AI on this part to know how to use map to find twin edge, and it works!
			}
			for (unsigned int i = 0; i < faceids.size(); i++) {
				hedges[i]->next = hedges[(i + 1) % faceids.size()];
				hedges[(i + 1) % faceids.size()]->prev = hedges[i];
			}
			f->adjacent_halfedge = hedges[0];//Reminder:do not use faceid[0] to access vertex
			faces.push_back(f);
			delete[] hedges;
		}
	}

	checkMesh();
	if (!faces.empty()) normalize();  // don't normalize profile-only meshes (e.g. for Revolution)

	return true;
}


void myMesh::computeNormals()
{
	for (unsigned int i = 0; i < faces.size(); ++i) {
		myFace *f = faces[i];
		if (f && f->adjacent_halfedge) f->computeNormal();
	}

	for (unsigned int i = 0; i < vertices.size(); ++i) {
		myVertex *v = vertices[i];
		if (v && v->originof) v->computeNormal();
	}
}

void myMesh::normalize()
{
	if (vertices.size() < 1) return;

	int tmpxmin = 0, tmpymin = 0, tmpzmin = 0, tmpxmax = 0, tmpymax = 0, tmpzmax = 0;

	for (unsigned int i = 0; i < vertices.size(); i++) {
		if (vertices[i]->point->X < vertices[tmpxmin]->point->X) tmpxmin = i;
		if (vertices[i]->point->X > vertices[tmpxmax]->point->X) tmpxmax = i;

		if (vertices[i]->point->Y < vertices[tmpymin]->point->Y) tmpymin = i;
		if (vertices[i]->point->Y > vertices[tmpymax]->point->Y) tmpymax = i;

		if (vertices[i]->point->Z < vertices[tmpzmin]->point->Z) tmpzmin = i;
		if (vertices[i]->point->Z > vertices[tmpzmax]->point->Z) tmpzmax = i;
	}

	double xmin = vertices[tmpxmin]->point->X, xmax = vertices[tmpxmax]->point->X,
		ymin = vertices[tmpymin]->point->Y, ymax = vertices[tmpymax]->point->Y,
		zmin = vertices[tmpzmin]->point->Z, zmax = vertices[tmpzmax]->point->Z;

	double scale = (xmax - xmin) > (ymax - ymin) ? (xmax - xmin) : (ymax - ymin);
	scale = scale > (zmax - zmin) ? scale : (zmax - zmin);

	for (unsigned int i = 0; i < vertices.size(); i++) {
		vertices[i]->point->X -= (xmax + xmin) / 2;
		vertices[i]->point->Y -= (ymax + ymin) / 2;
		vertices[i]->point->Z -= (zmax + zmin) / 2;

		vertices[i]->point->X /= scale;
		vertices[i]->point->Y /= scale;
		vertices[i]->point->Z /= scale;
	}
}


void myMesh::splitFaceTRIS(myFace *f, myPoint3D *p)
{
	/**** TODO ****/
}

void myMesh::splitEdge(myHalfedge *e1, myPoint3D *p)
{

	/**** TODO ****/
}

void myMesh::splitFaceQUADS(myFace *f, myPoint3D *p)
{
	/**** TODO ****/
}


void myMesh::subdivisionCatmullClark()
{
	/**** TODO ****/
}

myHalfedge* myMesh::RevolutionMakeHE(int src_i, int dst_i, map<pair<int,int>, myHalfedge*> &twin_map)
{
	// make halfedge from src_i to dst_i, and set twin if exists in twin_map
	myHalfedge *e = new myHalfedge();
	e->source = vertices[src_i];
	vertices[src_i]->originof = e;
	halfedges.push_back(e);

	auto key = make_pair(dst_i, src_i);
	auto it = twin_map.find(key);
	if (it != twin_map.end()) {
		e->twin = it->second;
		it->second->twin = e;
	} else {
		twin_map[make_pair(src_i, dst_i)] = e;
	}
	return e;
}

void myMesh::RevolutionMakeFace(myHalfedge *ea, myHalfedge *eb, myHalfedge *ec)
{
	//make a new face with three halfedges
	myFace *f = new myFace();
	ea->next = eb; eb->prev = ea;
	eb->next = ec; ec->prev = eb;
	ec->next = ea; ea->prev = ec;
	ea->adjacent_face = eb->adjacent_face = ec->adjacent_face = f;
	f->adjacent_halfedge = ea;
	faces.push_back(f);
}

void myMesh::Revolution()
{
	if (faces.size() > 0) {
		cout << "Error! Revolution only works for meshes without faces!\n";
		return;
	}
	if (vertices.size() < 2) {
		cout << "Error! Need at least 2 vertices for revolution!\n";
		return;
	}

	int steps = 10;
	int size = (int)vertices.size(); // original profile vertex count
	double angleStep = 2.0 * M_PI / steps;

	// create rotated vertex columns.
	for (int i = 1; i < steps; i++) {
		double rad = i * angleStep;
		double cosA = cos(rad);
		double sinA = sin(rad);
		for (int j = 0; j < size; j++) {
			double x = vertices[j]->point->X;
			double z = vertices[j]->point->Z;
			myVertex *newV = new myVertex();
			newV->point = new myPoint3D(x * cosA - z * sinA,
			                            vertices[j]->point->Y,
			                            x * sinA + z * cosA);
			vertices.push_back(newV);
		}
	}

	// helper lambda: vertex index from (column, row)
	// got this by AI to make the code cleaner, and it works!
	auto idx = [&](int col, int row) {
		return (col % steps) * size + row;
	};

	// build all halfedges and faces.
	// For each quad strip between column i and column (i+1)%steps,
	// and each row segment j to j+1, we create 2 triangles:


	map<pair<int,int>, myHalfedge*> twin_map;

	// i struggle a lot in this part, and I asked AI to reform those idxs, it wrote a lambda for me and it works
	for (int i = 0; i < steps; i++) {
		int next_i = (i + 1) % steps;
		for (int j = 0; j < size - 1; j++) {
			int A = idx(i,      j);
			int B = idx(next_i, j);
			int C = idx(next_i, j + 1);
			int D = idx(i,      j + 1);

			// Triangle 1: A -> B -> C
			myHalfedge *e_AB = RevolutionMakeHE(A, B, twin_map);
			myHalfedge *e_BC = RevolutionMakeHE(B, C, twin_map);
			myHalfedge *e_CA = RevolutionMakeHE(C, A, twin_map);
			RevolutionMakeFace(e_AB, e_BC, e_CA);

			// Triangle 2: A -> C -> D
			myHalfedge *e_AC = RevolutionMakeHE(A, C, twin_map);
			myHalfedge *e_CD = RevolutionMakeHE(C, D, twin_map);
			myHalfedge *e_DA = RevolutionMakeHE(D, A, twin_map);
			RevolutionMakeFace(e_AC, e_CD, e_DA);
		}
	}

	// top cap: polygon face at row 0.
	{
		myFace *capFace = new myFace();
		vector<myHalfedge*> capEdges(steps);
		for (int i = 0; i < steps; i++) {
			int src = idx(steps - 1 - i, 0);
			int dst = idx(steps - 1 - ((i + 1) % steps), 0);
			capEdges[i] = RevolutionMakeHE(src, dst, twin_map);
			capEdges[i]->adjacent_face = capFace;
		}
		for (int i = 0; i < steps; i++) {
			capEdges[i]->next = capEdges[(i + 1) % steps];
			capEdges[(i + 1) % steps]->prev = capEdges[i];
		}
		capFace->adjacent_halfedge = capEdges[0];
		faces.push_back(capFace);
		triangulate(capFace);
	}

	// bottom cap: polygon face at row size-1.
	{
		int bot = size - 1;
		myFace *capFace = new myFace();
		vector<myHalfedge*> capEdges(steps);
		for (int i = 0; i < steps; i++) {
			int src = idx(i, bot);
			int dst = idx((i + 1) % steps, bot);
			capEdges[i] = RevolutionMakeHE(src, dst, twin_map);
			capEdges[i]->adjacent_face = capFace;
		}
		for (int i = 0; i < steps; i++) {
			capEdges[i]->next = capEdges[(i + 1) % steps];
			capEdges[(i + 1) % steps]->prev = capEdges[i];
		}
		capFace->adjacent_halfedge = capEdges[0];
		faces.push_back(capFace);
		triangulate(capFace);
	}

	checkMesh();
	normalize();
	cout << "Revolution done (side strips): " << vertices.size() << " vertices, "
		 << halfedges.size() << " halfedges, "
		 << faces.size() << " faces.\n";
}

void myMesh::simplify()
{
	//shortest edge collapse until we eliminated 20% of the vertices
	//asked ai for the data structure to store edge records,
	//and it suggested using a multiset to keep the edge records sorted by length

	// simplify assumes triangular faces, so triangulate first
	triangulate();

	multiset<EdgeRecord> edgeRecords;
	map<myHalfedge*, multiset<EdgeRecord>::iterator> edgeToRecord;
	for (myHalfedge* e : halfedges) {
		if (!e || !e->source || !e->twin || !e->twin->source) continue;
		double length = e->source->point->dist(*(e->twin->source->point));
		if (e < e->twin) {
			auto it = edgeRecords.insert({e, length});
			edgeToRecord[e] = it;
			edgeToRecord[e->twin] = it;
		}
	}

	//iterate untill the size we want
	//Delete from edgeRecord + Create new relationship + Delete Vertex and Halfedges
	double meshSize = vertices.size();
	int targetSize = (int)(meshSize * 0.8);
	int totalToRemove = (int)vertices.size() - targetSize;
	int removed = 0;
	while ((int)vertices.size() > targetSize) {
		if (edgeRecords.empty()) break;
		auto er = edgeRecords.begin();
		myHalfedge* he = er->he;
		edgeRecords.erase(er);
		edgeToRecord.erase(he);
		edgeToRecord.erase(he->twin);

		myVertex* vA = he->source;
		myVertex* vB = he->twin->source;

		// ============ Added by AI debugging : check if collapsing this edge would cause topological issues ==============
		vector<myVertex*> neighborsA;
		myHalfedge* currA_check = he;
		do {
			if (currA_check->twin) neighborsA.push_back(currA_check->twin->source);
			currA_check = currA_check->twin->next;
		} while (currA_check != he && currA_check != nullptr);

		vector<myVertex*> neighborsB;
		myHalfedge* currB_check = he->twin;
		do {
			if (currB_check->twin) neighborsB.push_back(currB_check->twin->source);
			currB_check = currB_check->twin->next;
		} while (currB_check != he->twin && currB_check != nullptr);

		int sharedCount = 0;
		for (auto nA : neighborsA) {
			for (auto nB : neighborsB) {
				if (nA == nB) sharedCount++;
			}
		}

		int expectedShared = 0;
		if (he->adjacent_face) expectedShared++;
		if (he->twin && he->twin->adjacent_face) expectedShared++;

		if (sharedCount != expectedShared) {
			continue;
		}
		// ============The end of the AI debugging===============

		myPoint3D* newV = new myPoint3D((vA->point->X + vB->point->X) / 2,
		                                (vA->point->Y + vB->point->Y) / 2,
		                                (vA->point->Z + vB->point->Z) / 2);
		vA->point = newV;

		myHalfedge* start = he->twin;
		myHalfedge* curr = start;
		do {
			curr->source = vA;
			auto recIt = edgeToRecord.find(curr);
			if (recIt != edgeToRecord.end()) {
				edgeRecords.erase(recIt->second);
				edgeToRecord.erase(recIt);
				edgeToRecord.erase(curr->twin);
			} else {
				auto recIt2 = edgeToRecord.find(curr->twin);
				if (recIt2 != edgeToRecord.end()) {
					edgeRecords.erase(recIt2->second);
					edgeToRecord.erase(recIt2);
					edgeToRecord.erase(curr);
				}
			}
			if (!curr->twin) break;
			curr = curr->twin->next;
		} while (curr != start);


		myHalfedge* e_next = he->next;
		myHalfedge* e_n_n  = e_next->next;
		myHalfedge* t_next = he->twin->next;
		myHalfedge* t_n_n  = t_next->next;

		// erase the edge records of the 6 halfedges that will be removed, if they exist
		for (myHalfedge* dying : {e_n_n, t_next}) {
			auto it1 = edgeToRecord.find(dying);
			if (it1 != edgeToRecord.end()) {
				edgeRecords.erase(it1->second);
				edgeToRecord.erase(it1);
				edgeToRecord.erase(dying->twin);
			} else {
				auto it2 = edgeToRecord.find(dying->twin);
				if (it2 != edgeToRecord.end()) {
					edgeRecords.erase(it2->second);
					edgeToRecord.erase(it2);
					edgeToRecord.erase(dying);
				}
			}
		}

		myHalfedge* en_twin  = e_next->twin;
		myHalfedge* enn_twin = e_n_n->twin;
		en_twin->twin  = enn_twin;
		enn_twin->twin = en_twin;

		myHalfedge* tn_twin  = t_next->twin;
		myHalfedge* tnn_twin = t_n_n->twin;
		tn_twin->twin  = tnn_twin;
		tnn_twin->twin = tn_twin;

		vA->originof = enn_twin;

		//delete the collapsed vertex, 2 faces and 6 halfedges
		vertices.erase(find(vertices.begin(), vertices.end(), vB));
		faces.erase(find(faces.begin(), faces.end(), he->adjacent_face));
		faces.erase(find(faces.begin(), faces.end(), he->twin->adjacent_face));
		halfedges.erase(find(halfedges.begin(), halfedges.end(), he));
		halfedges.erase(find(halfedges.begin(), halfedges.end(), he->twin));
		halfedges.erase(find(halfedges.begin(), halfedges.end(), e_next));
		halfedges.erase(find(halfedges.begin(), halfedges.end(), e_n_n));
		halfedges.erase(find(halfedges.begin(), halfedges.end(), t_next));
		halfedges.erase(find(halfedges.begin(), halfedges.end(), t_n_n));


		//update the edge records
		myHalfedge* startA = vA->originof;
		myHalfedge* currA  = startA;
		do {
			if (!currA || !currA->twin) break;
			if (edgeToRecord.find(currA)       == edgeToRecord.end() &&
			    edgeToRecord.find(currA->twin) == edgeToRecord.end()) {
				double length = currA->source->point->dist(*(currA->twin->source->point));
				myHalfedge* key = (currA < currA->twin) ? currA : currA->twin;
				auto it = edgeRecords.insert({key, length});
				edgeToRecord[currA]       = it;
				edgeToRecord[currA->twin] = it;
			}
			currA = currA->twin->next;
		} while (currA != startA);

		// Added the print progress by AI, because there was so many errors
		removed++;
		int barWidth = 40;
		float progress = (float)removed / totalToRemove;
		int filled = (int)(barWidth * progress);
		cout << "\rSimplifying [";
		for (int i = 0; i < barWidth; i++) cout << (i < filled ? '#' : '-');
		cout << "] " << removed << "/" << totalToRemove << "  " << flush;
	}
	cout << "\nSimplification done.\n";
	checkMesh();
}

void myMesh::simplify(myVertex *)
{
	/**** TODO ****/
}

void myMesh::triangulate()
{
	size_t originalFaceCount = faces.size();
	for (size_t i = 0; i < originalFaceCount; ++i) {
		triangulate(faces[i]);
	}
	computeNormals();
}

bool ifPointContainTriangle(myPoint3D* p1, myPoint3D* p2, myPoint3D* p3, myPoint3D* p) {
	if (!p1 || !p2 || !p3 || !p) return false;

	// Build edge vectors and point vectors
	myVector3D vAB = (*p2) - (*p1);
	myVector3D vAP = (*p) - (*p1);

	myVector3D vBC = (*p3) - (*p2);
	myVector3D vBP = (*p) - (*p2);

	myVector3D vCA = (*p1) - (*p3);
	myVector3D vCP = (*p) - (*p3);

	// Cross products for each edge with the vector to point
	myVector3D c1 = vAB.crossproduct(vAP);
	myVector3D c2 = vBC.crossproduct(vBP);
	myVector3D c3 = vCA.crossproduct(vCP);


	// Check that all cross products point to the same general direction:
	// dot products between them should be non-negative.
	double d12 = c1 * c2;
	double d13 = c1 * c3;
	double d23 = c2 * c3;

	return (d12 >= 0) && (d13 >= 0) && (d23 >= 0);
}

bool ifContainTriangle(myPoint3D* p1, myPoint3D* p2, myPoint3D* p3, const std::set<myVertex*>& vertices) {
	for (const myVertex* v : vertices) {
		if (!v || !v->point) continue;
		// skip the triangle's own vertices
		if (v->point == p1 || v->point == p2 || v->point == p3) continue;

		if (ifPointContainTriangle(p1, p2, p3, v->point)) {
			return true;
		}
	}
	return false;
}

bool ifPointsConvex(myPoint3D* p1, myPoint3D* p2, myPoint3D* p3, myVector3D* normal) {

	myVector3D v12 = (*p2) - (*p1);
	myVector3D v23 = (*p3) - (*p2);

	myVector3D cross = v12.crossproduct(v23);
	double product = cross * *normal;
	return product > 0;
}


//return false if already triangle, true othewise.
bool myMesh::triangulate(myFace *f)
{
	/**** keep existing triangulation logic ****/

	// Compute face normal BEFORE triangulating (needed for convexity check)
	f->computeNormal();

	// Set the Vertex set
	bool isCut = false;
	std::set<myVertex*> vertexSet;
	myHalfedge *curr = f->adjacent_halfedge;
	do {
		vertexSet.insert(curr->source);
		curr = curr->next;
	} while(curr != f->adjacent_halfedge);
	if (vertexSet.size() == 3) return false;


	myHalfedge *e1 = f->adjacent_halfedge;
	myHalfedge *e2 = e1->next;
	myHalfedge *e3 = e2->next;
	int totalIter = 0;
	int maxTotalIter = (int)vertexSet.size() * (int)vertexSet.size() * 4;
	while (vertexSet.size() >= 3) {
		// reset cut flag for this iteration
		isCut = false;
		if (!ifContainTriangle(e1->source->point, e2->source->point, e3->source->point, vertexSet) && vertexSet.find(e2->source) != vertexSet.end()) {
			// Split the face into two faces by edge e1->e3
			if (ifPointsConvex(e1->source->point, e2->source->point, e3->source->point, f->normal)) {
				if (vertexSet.size() == 3) {
				    //last triangle, just close the loop and assign face
				    e1->next = e2;
				    e2->prev = e1;
				    e2->next = e3;
				    e3->prev = e2;
				    e3->next = e1;
				    e1->prev = e3;

				    e1->adjacent_face = f;
				    e2->adjacent_face = f;
				    e3->adjacent_face = f;

				    f->adjacent_halfedge = e1;

				    vertexSet.clear();
				}
				else {
				    myHalfedge *e_prev = e1->prev;

				    myFace *newFace = new myFace();
				    myHalfedge *newEdge = new myHalfedge();
				    myHalfedge *newEdgeTwin = new myHalfedge();


				    newEdge->source = e3->source;
				    newEdgeTwin->source = e1->source;
				    newEdge->twin = newEdgeTwin;
				    newEdgeTwin->twin = newEdge;

				    newEdge->adjacent_face = newFace;
				    e1->adjacent_face = newFace;
				    e2->adjacent_face = newFace;

				    e1->next = e2;
				    e2->prev = e1;
				    e2->next = newEdge;
				    newEdge->prev = e2;
				    newEdge->next = e1;
				    e1->prev = newEdge;

				    newFace->adjacent_halfedge = e1;
				    newEdgeTwin->adjacent_face = f;

				    e_prev->next = newEdgeTwin;
				    newEdgeTwin->prev = e_prev;

				    newEdgeTwin->next = e3;
				    e3->prev = newEdgeTwin;

				    f->adjacent_halfedge = newEdgeTwin;


				    faces.push_back(newFace);
				    halfedges.push_back(newEdge);
				    halfedges.push_back(newEdgeTwin);

				    vertexSet.erase(e2->source);


				    e1 = newEdgeTwin;
				    e2 = e1->next;
				    e3 = e2->next;
					isCut = true;
				}
			}
		}
		if(!isCut) {
			e1 = e1->next;
			e2 = e2->next;
			e3 = e3->next;
			totalIter++;
			if (totalIter > maxTotalIter) {
				cout << "Warning: triangulation gave up on a face (likely non-planar or degenerate)." << endl;
				break;
			}
		}

	}
	// If we reached here the face has been (or attempted to be) triangulated
	return true;
}

